[package]
name = "swc_ffi"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
swc_common = "17.0.1"
swc_ecma_parser = "27.0.4"
swc_ecma_ast = "18.0.0"
swc_ecma_visit = "18.0.1"
serde = { version = "1.0.171", features = ["derive"] }
serde_json = "1.0"
anyhow = "1.0"